### ISSUE TITLE
[Enhancement Request] Add option to change sprint behavior to more modern one

### ISSUE THREAD

**Issue by Patrxgt** [catsmackaroo/LibertyTweaks#13]
It would be nice, if this mod could provide an option to activate more modern sprint mechanics (like in [this](https://www.nexusmods.com/reddeadredemption2/mods/704) mod), where simply pressing Shift would allow to toggle between walk and jogging mode and only actually holding it would make Niko/Luis/Johnny sprint at the full speed.

**Comment by catsmackaroo** [comment]
1.5 does implement some sprint stuff, those like other R* titles, but it's basically that old scripthook .net brought to iv sdk .net. i'll try to integrate your version here instead as it sounds much better. thank you

**Comment by Patrxgt** [comment]
I'm not saying, that you should implement my version instead of the old one. I'm saying, that you should add a choice if a player wants the sprint mechanics from the older games or the ones from the newer games.
