### ISSUE TITLE
Personal vehicle respawns below map after completing mission/reloading save file

### ISSUE THREAD

**Issue by UnknownOutlaw** [catsmackaroo/LibertyTweaks#15]
This is the location it spawns. It wont seem to spawn anywhere else no matter what I do. I always have to get a new car.

(Images for reference)

![Screenshot 2024-06-05 185306](https://github.com/catsmackaroo/LibertyTweaks/assets/171876355/29e474cd-12e1-4dbc-921b-5a9798f1c614)

![Screenshot 2024-06-05 185541](https://github.com/catsmackaroo/LibertyTweaks/assets/171876355/2bcaf28d-b118-4e9d-b57e-3a7026bdbe17)

**Comment by UnknownOutlaw** [comment]
Adding on to this, it will spawn near that same area on the road. Which is annoying because it would make more sense to spawn near niko

**Comment by catsmackaroo** [comment]
Should be fixed by now, thanks for the report
