### ISSUE TITLE
Bugs in Missions

### ISSUE THREAD

**Issue by Sebas7882** [catsmackaroo/LibertyTweaks#16]
Hi, love the mod, couldn't play IV without it.
Just an issue I discovered throughout mission play: NPCs sometimes tend to stuck in place, no reaction, no health bar, simply won't move. (However, reloading the save seems to solve this issue)
Also, in the mission "Babysitting", this bug makes it unplayable because Derrick keeps falling off the boat when shooting, retry 3 times, no luck, remove this mod seems to solve the issue.
If you have the time, please take a look at this, the previous version doesnt have this issue.
Thanks

**Comment by catsmackaroo** [comment]
Should be fixed in latest 1.5 Hotfix [here](https://github.com/catsmackaroo/LibertyTweaks/releases/tag/1.5)
