### ISSUE TITLE
If you switch weapon while reloading a shotgun or RPG, the shotgun shell/rocket model stays around. This also prevents more rocket models from appearing until the first despawns.

### ISSUE THREAD

**Issue by Haxogone** [catsmackaroo/LibertyTweaks#24]

**Comment by Haxogone** [comment]
<img width="1280" alt="Grand Theft Auto 4 Screenshot 2024 07 21 - 00 05 53 35" src="https://github.com/user-attachments/assets/64cc0a9f-9a6f-41a9-8ead-5537933f932c">

**Comment by Haxogone** [comment]
This also happens with shotgun shells.
<img width="1280" alt="Grand Theft Auto 4 Screenshot 2024 07 21 - 00 06 54 26" src="https://github.com/user-attachments/assets/a7bb88e5-b452-438b-b2bb-568672cae929">

**Comment by catsmackaroo** [comment]
Should be good now
