### ISSUE TITLE
Muliplayer Crashes the game

### ISSUE THREAD

**Issue by GTAGamingChannel44** [catsmackaroo/LibertyTweaks#26]
This mod is an essential thing to have when it comes to fix and improve the game, but it only has one issue, when I want to test mod in multiplayer via the phone, the game will crash before and after I pressed the button to launch any mode.

**Comment by Kev7cks** [comment]
Setting Sprint Fix to 0 fixed it for me.

**Comment by catsmackaroo** [comment]
This project isn't really designed for multiplayer. There's also a lot of variables to consider when it comes to that, e.g: GFWL, GTAC, etc. testing would be hard, especially as I'm mostly working on this project by myself atm. sorry for the inconvenience but I probably won't fix multiplayer stuff for awhile
