### ISSUE TITLE
Models from the Gun Magazine feature despawn boats

### ISSUE THREAD

**Issue by Haxogone** [catsmackaroo/LibertyTweaks#27]
I exit the boat, start shooting, and the boat disappears. What even causes this?

**Comment by Haxogone** [comment]
Turns out, gun magazine models despawn vehicles.

**Comment by catsmackaroo** [comment]
Should be fixed in 1.6 now. [Download](https://github.com/catsmackaroo/LibertyTweaks/releases/tag/1.6)
