### ISSUE TITLE
[Feature Request] Add Enemy Blips on radar

### ISSUE THREAD

**Issue by GTAGamingChannel44** [catsmackaroo/LibertyTweaks#30]
When I was testing this mod in missions, it was great, so I thought of requesting to add Enemy Blips on the radar and also the pause menu because this would be a great combination with the Improved AI and Health Regeneration so the player could know if the enemy is coming or not.

It is a great mod overall and I hope it adds more features in the future

**Comment by catsmackaroo** [comment]
Jotted this on my to-do list awhile back. Hoping I get to it eventually. Thank you for the suggestion
