### ISSUE TITLE
An error occured while processing 'GameLoadPriority' event for IV-SDK .NET script 'LibertyTweaks.Main'. Aborting

### ISSUE THREAD

**Issue by GXTVV** [catsmackaroo/LibertyTweaks#33]
This error happens everytime to me, I'm using patch 1.0.7.0, LibertyTweaks 1.6 and IV-SDK .NET v1.8, can someone help me? Screenshot from the error below!
![Screenshot 2024-12-07 223520](https://github.com/user-attachments/assets/9fae0ac7-c55a-43b1-ba5f-6a5f93a3cc52)

**Comment by Ex3cutionerX** [comment]
Same here. https://github.com/ClonkAndre/IV-SDK-DotNet/issues/28

**Comment by catsmackaroo** [comment]
If y'all are using Liberty Tweaks 1.6, try & redownload it as I've updated it. If it doesn't work, ensure you have [Clonk's Coding Library](https://github.com/ClonkAndre/ClonksCodingLib.GTAIV/releases/tag/v1.9) as well. Otherwise, not sure at the moment.

**Comment by GXTVV** [comment]
I have downgradade LibertyTweaks to 1.5 and IV-SDK .NET to 1.7 now the mod is working fine without errors in logs!

**Comment by Ex3cutionerX** [comment]
> If y'all are using Liberty Tweaks 1.6, try & redownload it as I've updated it. If it doesn't work, ensure you have [Clonk's Coding Library](https://github.com/ClonkAndre/ClonksCodingLib.GTAIV/releases/tag/v1.9) as well. Otherwise, not sure at the moment.

The new 1.6 fix works well with IV-SDK .NET 1.8 now, thanks.
