### ISSUE TITLE
Major Performance Issue with "Personal Vehicle" Enabled in LibertyTweaks

### ISSUE THREAD

**Issue by Ex3cutionerX** [catsmackaroo/LibertyTweaks#34]
After playing the game for more than 15 minutes, I began experiencing major stuttering, choppiness, noticeable lag, and FPS drops. The issue persisted even when I loaded a save or entered a new area. Initially, I thought it was caused by other graphical mods, so I started removing and testing without them, but the problem still persisted.

After extensive testing, I discovered that the problem was caused by the [Personal Vehicle] Enable=1 option in the LibertyTweaks.ini file. I found this because the IVSDKDotNet.log was flooded with PersonalVehicle triggers every time I entered a new vehicle. This seemed to be the root cause of the stuttering and severe FPS drops—from over 140 FPS to as low as 20 FPS!

Once I disabled the PersonalVehicle option in the LibertyTweaks.ini file, the stuttering and lag completely disappeared, and the game now runs smoothly without any issues.

I hope this information helps in identifying and resolving this problem. Thank you!

**Comment by catsmackaroo** [comment]
Appreciate the report. Are you using 1.5 or 1.6 currently?

**Comment by Ex3cutionerX** [comment]
I'm using Liberty Tweaks 1.6, but the issue also occurred with version 1.5. It took me some time to figure out that the Personal Vehicle feature was causing all this trouble. I'm running GTA IV 1.0.7.0 with the latest ZolikaPatch, IVSDK 1.8, DXVK, and CryENB V3. I don't use FusionFix because its graphical modifications are very basic compared to ENB shaders.

**Comment by catsmackaroo** [comment]
Can you do me a favor and redownload 1.6, and see how it is now? Also, ensure Verbose Logging is disabled in the .ini file.
