### ISSUE TITLE
Using the cellphone causes wanted level when Unholstered Wanted Fix=1

### ISSUE THREAD

**Issue by pr0statitis** [catsmackaroo/LibertyTweaks#6]
When I activate the Unholstered Wanted Fix, pulling out the cellphone in the vicinity of a cop causes a 1 star wanted level. 
Is the phone considered a weapon by the game?

**Comment by catsmackaroo** [comment]
Yeah it is. It's considered an object; like a brick, or a soda can. I have fixed this in **Liberty Tweaks 1.4**, but it's not released yet. 

If you want to use it early, update [IV SDK .NET](https://gtaforums.com/topic/986510-iv-sdk-net/), install the early IV SDK .NET 1.2 [dependency](https://github.com/catsmackaroo/LibertyTweaks/tree/main/Dependencies), then install [Liberty Tweaks 1.4](https://github.com/catsmackaroo/LibertyTweaks/releases/tag/1.4).

Keep note the dependency is 1.2 of IV SDK .NET, which is not officially released. Neither is 1.4 of Liberty Tweaks, so other issues may arise, but I've found none as of yet.
